"use client"

import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect } from 'react'
import styles from '@/app/[locale]/Home.module.css'
import { ContextStore } from '@/context/ContextStore'

const page = () => {
    const contextValues = useContext(ContextStore)
    if (!contextValues) {
        return null;
      }
    const {setReadyToPrint, readyToPrint, workInProgress, setWorkInProgress } = contextValues;

    useEffect(()=>{
      localStorage.setItem('Exodus_ReadyToPrint', JSON.stringify(readyToPrint))
      localStorage.setItem('Exodus_WorkInProgress', JSON.stringify(workInProgress))
    }, [workInProgress, readyToPrint])

    return (
        <div style={{ backgroundImage: 'url("/img/bg_light.png")' }} className={styles.container}>
          <Head>
            <title>Books By MagicWand</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
           
          </Head>
    
        <>
    
        <div style={{ backgroundImage: 'url("/img/bg_dark.png")' }} className="bg-cover bg-center w-[90%] md:w-[65%] pt-16 pb-4 mx-auto rounded-xl flex flex-col gap-6 justify-end mt-3">
          <h1 className='text-white text-center mediumText font-semibold text-4xl' >Select Category</h1>
    
          <div className="grid gap-3 mx-auto px-6 md:grid-cols-2 w-[60%] mt-[10px] md:mt-[50px] lg:mt-[100px]" >
          
            <Link href='/price-calculator/step_0'>
                <div onClick={()=>{setReadyToPrint(true); setWorkInProgress(false);}} className='bg-white rounded-lg h-[250px] p-5 hover:bg-blue-100 mb-8 md:mb-[0px] relative'  >
                    <img src='/img/book.png' className='mx-auto ' />
                    <div className='text-blue flex gap-4 items-center  absolute bottom-[10%] left-[50%] translate-x-[-50%] font-bold w-[80%] text-center'>
                    <img src="/img/printer.png" className="w-[40px]  h-[40px] bg-green-100 p-2 rounded-full" /> <p>Ready to Print?</p></div>
                    <input checked={readyToPrint} className="absolute top-0 right-0 m-3" type='checkbox'/>
                </div>
            </Link>

            <Link href='/price-calculator/step_0'>
                <div onClick={()=>{setReadyToPrint(false); setWorkInProgress(true);}} className='bg-white rounded-lg h-[250px] p-5 hover:bg-blue-100 mb-8 md:mb-[0px] relative'>
                    <img src='/img/book.png' className='mx-auto ' />
                    <div className='text-blue flex gap-4 items-center  absolute bottom-[10%] left-[50%] translate-x-[-50%] font-bold w-[80%] text-center'>
                    <img src="/img/wip.png" className="w-[40px]  h-[40px] bg-red-100 p-2 rounded-full" /> <p>Work in progress?</p></div>
                    <input checked={workInProgress} className="absolute top-0 right-0 m-3" type='checkbox'/>
                </div>
            </Link>

          </div>
        </div>
       
        </>
    
            
        </div>
      )
}

export default page
