"use client";

import React, { useContext, useEffect } from "react";
import { ContextStore } from "@/context/ContextStore";
import Head from "next/head";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import styles from "@/app/[locale]/Home.module.css";

export default function PriceCalculator () {
  const contextValues = useContext(ContextStore);

  if (!contextValues) {
    return null;
  }

  const { setMagazine, magazine, setBook, book, setStationary, stationary } = contextValues;

  useEffect(()=>{
    localStorage.setItem("Exodus_Book", JSON.stringify(book));
    localStorage.setItem("Exodus_Magazine", JSON.stringify(magazine));
    localStorage.setItem("Exodus_Stationary", JSON.stringify(stationary));
  }, [book, magazine, stationary]);

  return (
    <div>
      <Navbar/>

      <div style={{ backgroundImage: "url(\"/img/bg_light.png\")" }} className={styles.container}>

        <Head>
          <title>Books By MagicWand</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>

        <>

          <div style={{ backgroundImage: "url(\"/img/bg_dark.png\")" }} className="bg-cover bg-center w-[90%] md:w-[65%] pt-16 pb-4 mx-auto rounded-xl flex flex-col gap-6 justify-end mt-3">
            <h1 className="text-white text-center mediumText font-semibold text-4xl" >What will you like to print?</h1>

            <div className="grid gap-3 mx-auto px-6 md:grid-cols-2 lg:grid-cols-3 w-[80%] mt-[10px] md:mt-[50px] lg:mt-[100px]" >

              <div onClick={()=>{setBook(true);setMagazine(false); setStationary(false);}} className="bg-white rounded-lg h-[30vh] md:h-[280px] p-5 relative hover:bg-blue-100 mb-8 md:mb-[0px]">
                <Link href="price-calculator/project_readiness" >
                  <img src="/img/book.png" className="mx-auto " />
                </Link>
                <Link href="price-calculator/project_readinessk" >
                  <h1 className="text-blue block absolute bottom-[10%] left-[50%] translate-x-[-50%] font-bold w-[60%] text-center">Books</h1>
                </Link>
              </div>

              <div onClick={()=>{setBook(false);setMagazine(true); setStationary(false);}} className="bg-white rounded-lg h-[280px] p-5 relative hover:bg-blue-100 mb-8 md:mb-[0px]">
                <Link href="price-calculator/project_readiness" >
                  <img src="/img/magazine.png"className="mx-auto "  />
                </Link>
                <Link href="price-calculator/project_readiness" >
                  <h1 className="text-blue block absolute bottom-[10%] left-[50%] translate-x-[-50%] font-bold w-[60%] text-center">Magazines</h1>
                </Link>
              </div>
              <div onClick={()=>{setBook(false);setMagazine(false); setStationary(true);}} className="bg-white rounded-lg h-[280px] p-5 relative hover:bg-blue-100 mb-8 md:mb-[0px]">
                <Link href="price-calculator/project_readiness" >
                  <img src="/img/stationery.png" className="mx-auto " />
                </Link>
                <Link href="price-calculator/project_readiness" >
                  <h1 className="text-blue block absolute bottom-[10%] left-[50%] translate-x-[-50%] font-bold w-[60%] text-center">Office Stationaries</h1>
                </Link>
              </div>
            </div>
          </div>

        </>

      </div>
    </div>
  );
}
